### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'scrollWidth')

### ISSUE THREAD

**Issue by ChTayyab786** [rfmiotto/react-use-draggable-scroll#1]
TypeError: Cannot read properties of undefined (reading 'scrollWidth')
(anonymous function)
E:/newfolder/src/index.tsx:31
  28 | let cursorStyleOfChildElements: string[];
  29 | 
  30 | useEffect(() => {
> 31 |   maxHorizontalScroll = ref.current.scrollWidth - ref.current.clientWidth;
     | ^  32 |   maxVerticalScroll = ref.current.scrollHeight - ref.current.clientHeight;
  33 | 
  34 |   cursorStyleOfWrapperDiv = window.getComputedStyle(ref.current).cursor;
View compiled
▶ 22 stack frame

**Comment by rfmiotto** [comment]
Dear @ChTayyab786, I couldn't replicate this error on my local machine, but I believe that this error was being caused by the `useEffect` hook. As I was taking screen measurements, the proper hook should have been `useLayoutEffect`. I published an updated version with this fix. So, if possible, please go check if the code is now working properly. If the problem persists, let me know.

Notice, though, that with `useLayoutEffect`, the component cannot be rendered in the server. You might face some errors if you are using SSR. However, there are some workarounds:
[This thread](https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85), for instance, demonstrates how you can lazily show components that have `useLayoutEffect`.

**Comment by ChTayyab786** [comment]
> Dear @ChTayyab786, I couldn't replicate this error on my local machine, but I believe that this error was being caused by the `useEffect` hook. As I was taking screen measurements, the proper hook should have been `useLayoutEffect`. I published an updated version with this fix. So, if possible, please go check if the code is now working properly. If the problem persists, let me know.
> 
> Notice, though, that with `useLayoutEffect`, the component cannot be rendered in the server. You might face some errors if you are using SSR. However, there are some workarounds:
> [This thread](https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85), for instance, demonstrates how you can lazily show components that have `useLayoutEffect`.

**Comment by ChTayyab786** [comment]
TypeError: Cannot read properties of undefined (reading 'scrollWidth')
(anonymous function)
E:/newfolder/src/index.tsx:31
  28 | let cursorStyleOfChildElements: string[];
  29 | 
  30 | useLayoutEffect(() => {
> 31 |   maxHorizontalScroll = ref.current.scrollWidth - ref.current.clientWidth;
     | ^  32 |   maxVerticalScroll = ref.current.scrollHeight - ref.current.clientHeight;
  33 | 
  34 |   cursorStyleOfWrapperElement = window.getComputedStyle(ref.current).cursor;

**Comment by rfmiotto** [comment]
Hi, @ChTayyab786 

It seems that the reference is not defined. Just checking, are you passing the reference to the element, like in the example below?

```javascript
const ref = useRef();
const { events } = useDraggable(ref);

return (
    <div
      {...events} // add events
      ref={ref}    // add reference
    >
       ...
    </div>
);
```

If you are doing this already, then, could you provide more information so I can replicate the behavior here?

**Comment by ChTayyab786** [comment]
yes i did it same as you mention above. if it works fine on your machine then its ok. maybe there could be some other issue with my code.....
Thanks a lot.

**Comment by rfmiotto** [comment]
Hi, @ChTayyab786 

I am sorry for that.
The reason I created this package was to achieve a lightweight and performative solution for mimicking this drag behavior.
However, there are other approaches out there that you could try, which are far more sophisticated then mine.
For instance, you can try using [Framer Motion](https://www.framer.com/motion/) & [use-gesture](https://use-gesture.netlify.app/). Their documentation are really great and there are dozens of great tutorials online.

Best

**Comment by ChTayyab786** [comment]
I appreciate your help, Thank You  @rfmiotto .

**Comment by meotimdihia** [comment]
I am getting this error. My Sentry reported it. I couldn't reproduce it but it happened.

**Comment by meotimdihia** [comment]
@rfmiotto you revert this bug in recent changes.

**Comment by rfmiotto** [comment]
Hi @meotimdihia,

Thank you very much for the heads up!
I reverted this change and publish the updated package under version 0.4.3.
I also added hack to avoid a big useLayoutEffect warning from showing up in the console when using SSR. 

Hope it works now!
But if the error continues, please let me know.

**Comment by meotimdihia** [comment]
@rfmiotto thanks for the fixes. 🙏
