### ISSUE TITLE
Text highlighting

### ISSUE THREAD

**Issue by Lakelimbo** [rfmiotto/react-use-draggable-scroll#17]
Hey!
Sorry if I'm missing something here, but I noticed that whenever I add a div with the useDraggable, it prevents text-highlighting with the mouse in the entire page, even outside of the divs with scroll, at least on Chromium-based browsers.
After looking for a while, I'm pretty sure it's not a CSS issue either.

**Comment by rfmiotto** [comment]
Hi @Lakelimbo 

Thank you for the heads up! This problem was caused by a previous fix #16.
I will revert this change. However, it was already published on NPM registry (v0.4.6). 
To avoid this problem, please, use the previous version instead ( 0.4.5 ).

**Comment by rfmiotto** [comment]
Dear @Lakelimbo 

Unfortunately, it is not possible to unpublish v0.4.6 from NPM.

So, to avoid other users having similar problems with this version (0.4.6), I published a new  one (0.4.7) which is exactly the same as v0.4.5.
