### ISSUE TITLE
[Feature request] Sensitivity to start drag

### ISSUE THREAD

**Issue by BrainCrumbz** [rfmiotto/react-use-draggable-scroll#2]
Hi there, thanks for having created this component. We just started using it and it is very simple and straightforward to use, plus it does not interfere with other events passing through the same scroll container, which is great.  
To the actual question:

Scenario:  
User clicks/taps on some element included in scroll container, in order to perform some action on it. 
It is relatively easy for her/him to actually move mouse a little while still keeping mouse button clicked (or finger pressed). Basically it is easy to start an unwanted drag operation.
When mouse button/finger is released, a short unnoticeable drag operation has happened, but no click has happened. _Correctly_ IMHO, the click event is "captured" by the drag operation and thus not passed to other components. 

Would it be possible to add a sensitivity input parameter, e.g. expressed in pixels or in a time duration? So that:
- when mouse move events arrive after mouse down, and minimum scrolling distance/time has not passed, the actual drag and scroll operation is not actually performed
- _case A)_ when further mouse events arrive and threshold is overcome, the drag and scroll operation kicks in and so scroll position "catches up" to where it should have been
- _case B)_ when instead a mouse up event arrives with threshold not overcome, drag and scroll operation has never actually started and is aborted. Instead, and here lies the detail, mouse up event is propagated, so to allow click detection by other handlers.

Does this makes sense?

We were looking and main library `index.ts` file, I guess conceptually this feature introduces an additional state in the state machine. Now there are 2 of them: is not dragging / is dragging. With such feature there would be 3: is not dragging / waiting for threshold / is dragging.

We could submit a PR too, if you could provide some explanation on the main gist of code.

Thanks anyway

**Comment by BrainCrumbz** [comment]
Could something like the following fit the bill? 
To the purpose of exemplifying, here sensitivity is taken a constant.

```ts
   // [omitted]

  const onMouseMove = (e: MouseEvent) => {
    if (!internalState.current.isMouseDown) {
      return;
    }

    e.preventDefault();

    const dx = internalState.current.lastMouseX - e.clientX;
    const dy = internalState.current.lastMouseY - e.clientY;

    const isBelowThreshold = (Math.abs(dx) < START_DRAG_DISTANCE) &&
      (Math.abs(dy) < START_DRAG_DISTANCE);

    if (isBelowThreshold) {
      return;
    }

    internalState.current.lastMouseX = e.clientX;
    internalState.current.scrollSpeedX = dx / timing;
    internalState.current.isDraggingX = true;

    internalState.current.lastMouseY = e.clientY;
    internalState.current.scrollSpeedY = dy / timing;
    internalState.current.isDraggingY = true;

    ref.current.style.cursor = "grabbing"; // eslint-disable-line no-param-reassign
    (ref.current.childNodes as NodeListOf<HTMLOptionElement>).forEach(
      (child: HTMLElement) => {
        child.style.cursor = "grabbing"; // eslint-disable-line no-param-reassign
      }
    );

    runScroll();
  };

  const START_DRAG_DISTANCE = 10;
  
   // [omitted]
```

What do you think about it?
Thanks

**Comment by rfmiotto** [comment]
Hi there!

I am very happy to hear your feedback. It would be a pleasure to have your contribution!

I hadn't thought about this possible scenario you described, and in fact it would be an interesting feature to add to the code.

I tested your suggestion, but unfortunately I noticed that it ends up creating a little strange behavior. When the user scrolls a little and then releases the mouse button, the container scrolls with an unexpectedly high speed. This is related to how the code calculates momentum.

I imagine it would be possible to achieve this behavior within the `onMouseUp` function. In this function the click events are blocked while dragging. Implementing a checker for unwanted scrolls in this function seems to be a solution to this issue with the momentum. Besides, it has the benefit of avoiding too many state changes with every mouse movement.

We can then put a conditional inside `onMouseUp` function so that it blocks clicking events only if the movement is indeed intentional (using the threshold that you proposed). 

The first thing we need to do is add new states that store the mouse position at the moment of the click:
```typescript
  // [omitted]

  const internalState = useRef({
    isMouseDown: false,
    isDraggingX: false,
    isDraggingY: false,
    initialMouseX: 0, // HERE
    initialMouseY: 0, // HERE
    lastMouseX: 0,
    lastMouseY: 0,
    scrollSpeedX: 0,
    scrollSpeedY: 0,
    lastScrollX: 0,
    lastScrollY: 0,
  });

  // [omitted]
```

Then we can modify the onMouseUp function:
```typescript
  const onMouseUp = (e: MouseEvent) => {
    const isDragging =
      internalState.current.isDraggingX || internalState.current.isDraggingY;

    const dx = internalState.current.initialMouseX - e.clientX;
    const dy = internalState.current.initialMouseY - e.clientY;

    const isMotionIntentional =
      Math.abs(dx) > safeDisplacement || Math.abs(dy) > safeDisplacement;

    if (isDragging && isMotionIntentional) {
      ref.current.childNodes.forEach((child) => {
        child.addEventListener("click", preventClick);
      });
    } else {
      ref.current.childNodes.forEach((child) => {
        child.removeEventListener("click", preventClick);
      });
    }

  // [omitted]
```
The `safeDisplacement` variable would be your `START_DRAG_DISTANCE`.

Please let me know what you think of this approach. I hope it works as expected.

You can make a pull request if you want. I would love to have your contribution.

If you also find it interesting, you can leave `safeDisplacement` as an input with a default value of 10 (or any other).

Thank you very much for supporting this project and please feel free to propose additional improvements!

**Comment by rfmiotto** [comment]
Oops, I forgot to set the initial states por X and Y position (`initialMouseX` and `initialMouseY`)...
We have to do it in the `onMouseDown` function:

```typescript
  const onMouseDown = (e: React.MouseEvent<HTMLElement>) => {
    const isLeftMouseButton = e.buttons === 1;
    if (!isLeftMouseButton) {
      return;
    }

    internalState.current.isMouseDown = true;
    internalState.current.lastMouseX = e.clientX;
    internalState.current.lastMouseY = e.clientY;
    internalState.current.initialMouseX = e.clientX; // HERE
    internalState.current.initialMouseY = e.clientY; // HERE
  };
```

**Comment by BrainCrumbz** [comment]
Hi. Thanks for quick reply. Your approach seems quite sensible.

There were also thoughts about how to fix our initial approach in order to take into account for momentum (e.g. store the initial time, and then use it to calculate time difference in place of `timing` when calculating scroll speed). But all in all that approach started to seem quite more convoluted and possibly broken anyway.

We tried your latest changes "on the fly" in a local copy of the component and all seems fine. Actually, when adding a temporary log here:

```ts
    if (isDragging && isMotionIntentional) {
      ref.current.childNodes.forEach((child) => {
        child.addEventListener("click", preventClick);
      });
    } else {
      console.log('NOT intentional'); // HERE
      ref.current.childNodes.forEach((child) => {
        child.removeEventListener("click", preventClick);
      });
    }
```

one can see that many apparent clicks are actually consequences of not intentional drags. Which seems to confirm initial theory.

Ok, we'll go with such a PR. Thanks again

**Comment by BrainCrumbz** [comment]
Does it make sense to still invoke `callbackMomentum` when `isDragging && isMotionIntentional` is false?

Not sure when `isDragging` is false, but when `isMotionIntentional` is false it seems a little counterintuitive for consumer application (and for user?) to perform its intended click action, but still see some inertial drag.

What do you think?

A proposed change could then be:

```ts
    // ... in onMouseUp
    const isDraggingConfirmed = isDragging && isMotionIntentional; // or some other name

    if (isDraggingConfirmed) {
      ref.current.childNodes.forEach((child) => {
        child.addEventListener("click", preventClick);
      });
    } else {
      ref.current.childNodes.forEach((child) => {
        child.removeEventListener("click", preventClick);
      });
    }

    internalState.current.isMouseDown = false;
    internalState.current.lastMouseX = 0;
    internalState.current.lastMouseY = 0;

    ref.current.style.cursor = cursorStyleOfWrapperElement; // eslint-disable-line no-param-reassign
    (ref.current.childNodes as NodeListOf<HTMLOptionElement>).forEach(
      (child: HTMLElement, i) => {
        child.style.cursor = cursorStyleOfChildElements[i]; // eslint-disable-line no-param-reassign
      }
    );

    if (isDraggingConfirmed) {
      callbackMomentum();
    }
```

**Comment by rfmiotto** [comment]
Hi there!

You are absolutely right, there is no need to invoke `callbackMomentum` when dragging is not intentional. Well noticed! 
Your solution is great, thank you very much.

If you want, feel free to create a PR with these changes. If not, please let me know so I can include them.

**Comment by BrainCrumbz** [comment]
We're already up with a dedicated branch: https://github.com/BrainCrumbz/react-use-draggable-scroll/tree/feat/drag-sensitivity.

Let us add that check on `callbackMomentum`, then we'll submit a PR.
