### ISSUE TITLE
For me draggable has stopped functioning properly

### ISSUE THREAD

**Issue by patriksramoss** [rfmiotto/react-use-draggable-scroll#25]
Since around April 2024 the draggable no longer functions properly. Once I hold the mouse click to start scrolling/dragging the scroll is locked and only when I release mouse it starts scrolling/dragging. Only had this issue before on Firefox but looks like Chrome suffers from this as well... Might try to fix this but if anyone knows any other alternative to react-use-draggable-scroll let me know!

**Comment by Fondson** [comment]
I had the same problem and this solution worked for me https://stackoverflow.com/a/53048959
Trying adding the following prop to the children of the wrapping div
```tsx
onDragStart={(e) => { e.preventDefault() }}
```

**Comment by patriksramoss** [comment]
> I had the same problem and this solution worked for me https://stackoverflow.com/a/53048959 Trying adding the following prop to the children of the wrapping div
> 
> ```tsx
> onDragStart={(e) => { e.preventDefault() }}
> ```

This worked, thank you Fondson!
