### ISSUE TITLE
[Problem] keepMovingX invoked after router unmounts component

### ISSUE THREAD

**Issue by BrainCrumbz** [rfmiotto/react-use-draggable-scroll#4]
Hi again.

Not sure if you need a repro project for this, will try to describe what we're experiencing.

**Version:**  
0.4.0

**Browser:**  
Windows Chrome

**Steps to reproduce:**
1. Project setup
   * Set up a react app to use react router v6
   * Have an app or sub-component with a router `Outlet` and two `Route`s, the first as default index route. Have some links to navigate from first route to the second
   * In the first route, have a component, say `MainCanvas`, which in turns shows some overflowing content and uses `useDraggable`
2. Launch app
3. Within `MainCanvas`, drag content a little
4. Browse to the second route

**What should happen:**
Browser DevTools console should show no errors

**What actually happens:**
Browser DevTools console shows an always-growing list of errors. It keeps on repeating the following messages:

```
12:12:59.874 main.ff8383e8.js:2 Uncaught TypeError: Cannot read properties of null (reading 'scrollLeft')
    at main.ff8383e8.js:2:430029
(anonymous) @ main.ff8383e8.js:2
setInterval (async)
(anonymous) @ main.ff8383e8.js:2
S @ main.ff8383e8.js:2
12:12:59.875 main.ff8383e8.js:2 Uncaught TypeError: Cannot read properties of null (reading 'scrollTop')
    at main.ff8383e8.js:2:430279
(anonymous) @ main.ff8383e8.js:2
setInterval (async)
(anonymous) @ main.ff8383e8.js:2
S @ main.ff8383e8.js:2
```

For *scrollLeft* case, the culprit line highlighted in DevTools is the following, in `keepMovingY` interval body:

![error-line](https://user-images.githubusercontent.com/3185573/156421641-8d0f0ce6-fcb3-4bc1-8245-6498852dbb66.png)

Probably, for the *scrollTop* case the culprit lies within `keepMovingY` body.

The immediate issue is that there's no check for `ref.current` being null or not. But then the question arises: why is `keepMovingX` (or Y) interval still invoked? Does `useDraggable` keeps things lingering around even after client component is unmounted? Or maybe is the client component fault (`MainCanvas` in this example)?

**Comment by rfmiotto** [comment]
Hi,

Thank you for reporting this issue. 

I tried to reproduce these errors by following your steps, but I didn't find any. Could you please take a look at the following example project I used to reproduce the problem to see if something comes up for you?
https://github.com/rfmiotto/reproducting-error

If you can, please send me a code so I can try to reproduce the problem on my local machine.

As you pointed out, when the component is unmounted, the event listeners are removed. So it is not clear to me what is causing this problem.

I don't think this is your case, but something I've noticed is that useDraggable is having some issues when used alongside Suspense from React 18. This is something to be aware of. In the near future, I will take a closer look at this issue.

All the best,
Renato

**Comment by BrainCrumbz** [comment]
Hi, thanks for your reply. Is that project still available to try? The link sends to 404 page.

**Comment by rfmiotto** [comment]
Ops, sorry about that.. there was a typo in the previous link. Here follows the correct one:
https://github.com/rfmiotto/reproducing-error

This is a simple CRA that uses react-router v6. I tried to reproduce the app you described, but I am not sure if I got it right. Nonetheless, I found no error in this example project. 
If you could provide more details about your setup, it would be helpful (or maybe even implementing the missing features in this example project so that I can see the error).

**Comment by BrainCrumbz** [comment]
Thanks, will try with that. 

BTW, on a separate topic, here below are two basic samples readily available in CodeSandbox and StackBlitz. Do you think it might be useful to point at them somewhere in readme page? Or you might want to create and share your own, of course.

* [CodeSandbox](https://codesandbox.io/s/react-use-draggable-scroll-basic-example-ymi0rm)
* [StackBlitz](https://stackblitz.com/edit/react-pxetxb?file=src/App.js)

**Comment by rfmiotto** [comment]
Hi @BrainCrumbz,

I  loved the examples you made. Adding them into README page would be great, for sure. Thanks a lot!

Recently I fixed a small bug related to CSS styles when using rubber band effect. I have already pushed this version to GitHub but didn't publish it just yet.

Maybe we can ship these examples in a next NPM package version (0.4.1).
Before publishing this new version though, I think we should try to fix this problem you are experiencing now.

**Comment by BrainCrumbz** [comment]
Ok, we arrived to a point where the issue happens in a basic enough (I think) project. BUT, we still cannot find the exact steps in order to reproduce it. Details follow.

We modified the basic StackBlitz sample in order to add: 
* 3 routes leading to 2 components, 
* a navbar to browse between them, 
* a click handler in container in order to change some of its state and force re-render 
* a click handler in contained box in order to change some of its state and force also a re-layout

The issue has something to do with the browser window losing and then re-gaining focus.

Here are the steps:

1. open StackBlitz project in Chrome at https://stackblitz.com/edit/react-1rtlwz?file=src%2FApp.js. Then *Open in New Window* its "viewable" page (it will open at https://react-1rtlwz.stackblitz.io/).
   * Side note: when we succeeded to reproduce issue in our test, DevTools where undocked into a separate window 
3. in that newly opened page, click a couple of times on boxes, drag to scroll a couple of times
   * Obviously this is the part where we still have no clear steps on how to reproduce
5. leave browser and move to some other application, e.g. a text editor, Explorer. Not sure if this makes a difference
6. return to browser window, click on *Other component* navigation link

**What should happen**  
Page should show content of the other component.

**What actually happens**  
StackBlitz "overrides" the normal console behaviour, in the sense that console error messages are shown directly in the web page. Thus the page is constantly refreshed with a message like the following:

```
Error in /turbo_modules/react-use-draggable-scroll@0.4.0/dist/react-use-draggable-scroll.cjs.development.js (115:33)
Cannot read properties of null (reading 'scrollTop')
```

In retrospective, this is similar to what happens in our original project, where at some point a click on an button causes Window system *Open file* dialog to show, and that means the browser looses focus.

**Comment by BrainCrumbz** [comment]
Ok, steps found:

1. open StackBlitz project "viewable" page at https://react-1rtlwz.stackblitz.io/. DevTools are open undocked in a separate window, showing their Console tab. Both windows are visible, at least partially, so one can click directly on one or the other
2. click on item 1, so it gets larger
3. click in DevTools undocked window, so main page looses focus
4. click in main page on item 1, so main page re-gain focus and at the same time item turns to original size
5. click on *Other component* navigation link

Those seems to always "work" (i.e. reproduce issue again and again).

Edit: (thankfully?) it reproduces independently of what is the other window. E.g. Firefox page, a Windows command prompt, VS Code.

**Comment by BrainCrumbz** [comment]
Demo video:

https://user-images.githubusercontent.com/3185573/157033960-803cf051-7acc-424f-9030-ce6c450c7e09.mp4

**Comment by rfmiotto** [comment]
Hi @BrainCrumbz,

Thank you for sending the video.
I was just trying to reproduce it following your steps, but here it is working just fine.

I used Chrome Version 98.0.4758.102
https://user-images.githubusercontent.com/35971460/157033947-1cdd4fd9-3887-4b62-ab10-7390b60a6ef6.mp4

and also Firefox Version 97.0.2
https://user-images.githubusercontent.com/35971460/157034505-5a1ab8db-514f-47e9-bb08-59efa3c2114d.mp4

I am working on the cause of this problem now.
May I ask you what browser are you using?

And, if possible, could you roll back to a previous version of react-use-draggable-scroll to see if this error still occurs? You can do like:

`npm i react-use-draggable-scroll@0.2.3`

`yarn add react-use-draggable-scroll@0.2.3`

Thanks!

**Comment by rfmiotto** [comment]
Hi @BrainCrumbz,

The problem you are facing is probably related to some side effects.
I made some changes to clear the setIntervals and Timeouts from the code. The idea behind this is to remove our reference from the unmounted component, which is likely to be the cause of this problem.

I am not sure if this approach will work since I could not reproduce the issue here.
However, I added this candidate solution to this forked StackBlitz project:

https://stackblitz.com/edit/react-yj6bsz?file=src/react-use-draggable-scroll.js

Could you please see if it is working as expected?

**Comment by BrainCrumbz** [comment]
> May I ask you what browser are you using?

For sure it happened on Google Chrome on Windows. Chrome just updated its own version when I went checking for it, now it's 99.0.4844.51 64 bit and it still happens. Issue never showed up on Firefox in our app, and it does not seem to happen in our sample StackBlitz project as well.

Will try with your forked project with fix and let you know. Thanks

**Comment by BrainCrumbz** [comment]
Ok: tried the same steps in same browser with your modified StackBlitz, and the issue does *not* show up.

Actually, thinking about it, it could be interesting to try this modified version directly in our project.

*EDIT:* And, yes, repeating the repro steps valid effective for our project, the issue does not show up.

**Comment by rfmiotto** [comment]
It's great to hear that!

@BrainCrumbz, I have just published a new version to npm with this fix. The latest version is now 0.4.2

Thank you again for supporting this project!
And do not hesitate to propose further improvements or report any issues in the future!

**Comment by BrainCrumbz** [comment]
Thanks to your work, actually. 

From the maintenance point of view, so to say:
* One important thing could be to apply git tags on commits used to publish new versions of the package. It seems like there are no public tags at the moment, so it's not easy to figure which code shipped with which version.
* As a secondary step, one could opt to create a [new GitHub Release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) together with a new tag when publishing a new package version.

From the documentation point of view: 
* ~~As mentioned above, providing a link to a StackBlitz/CodeSandbox sample project in readme or in some other place visibile to newcomers, could be an idea.~~
* As a secondary step, providing a link from GitHub to the actual npm package page could be useful: there are several React scroll-related packages on npm, with such a link one could be sure to pick the actual npm package. The link could be established by showing a badge on top of readme page, as those generated by [Shields.io](https://shields.io/) and explained in their [Quickstart](https://github.com/badges/shields#quickstart). 

These are just some ideas coming to mind, and as you might noticed they're not focused on new features, but more on "rounding up" things. HTH

**Comment by rfmiotto** [comment]
Hi @BrainCrumbz,

Thank you very much for the valuable suggestions!

I will definitely incorporate them in the following days.
However, I've never added tags or set up GitHub releases before, so it might take a little bit longer for me to do that.

All the best,
Renato

**Comment by BrainCrumbz** [comment]
Re. tags: you can add a tag to your local repository through your preferred git client (command line, Fork... whatever), then make sure to push also tags when doing a push from local to remote. As an alternative, on GitHub you can add a new Release and at the same time add a new tag as well, directly on remote repo so to say. In this case, the next time you fetch/pull from remote to local, you'll see the tags locally as well.

Re. badge: we might create a tiny PR to add that to readme, if you prefer.

**Comment by rfmiotto** [comment]
Hi @BrainCrumbz,

Thanks for the explanation!
We can totally make a PR with that.
